backend: pytorch
context_servers:
  num_instances: 1
  urls:
  - lyris0175:8000
generation_servers:
  num_instances: 4
  urls:
  - lyris0163:8000
  - lyris0165:8001
  - lyris0169:8002
  - lyris0171:8003
hostname: lyris0163
port: 8333
