backend: pytorch
context_servers:
  num_instances: 6
  urls:
  - lyris0243:8000
  - lyris0244:8001
  - lyris0245:8002
  - lyris0246:8003
  - lyris0248:8004
  - lyris0249:8005
generation_servers:
  num_instances: 1
  urls:
  - lyris0235:8000
hostname: lyris0235
port: 8333
