backend: pytorch
context_servers:
  num_instances: 1
  urls:
  - lyris0230:8000
generation_servers:
  num_instances: 3
  urls:
  - lyris0223:8000
  - lyris0225:8001
  - lyris0227:8002
hostname: lyris0223
port: 8333
