backend: pytorch
context_servers:
  num_instances: 1
  urls:
  - lyris0126:8000
generation_servers:
  num_instances: 3
  urls:
  - lyris0120:8000
  - lyris0122:8001
  - lyris0124:8002
hostname: lyris0120
port: 8333
