allreduce_strategy: MNNVL
cache_transceiver_config:
  backend: DEFAULT
  max_tokens_in_buffer: 131104
  transceiver_runtime: CPP
cuda_graph_config:
  batch_sizes:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
  enable_padding: true
enable_attention_dp: false
kv_cache_config:
  dtype: fp8
  enable_block_reuse: false
  free_gpu_memory_fraction: 0.4
max_batch_size: 1
max_num_tokens: 128
max_seq_len: 139296
moe_config:
  backend: TRTLLM
moe_expert_parallel_size: 8
num_postprocess_workers: 4
pipeline_parallel_size: 1
print_iter_log: true
stream_interval: 20
tensor_parallel_size: 8
