backend: pytorch
context_servers:
  num_instances: 3
  urls:
  - lyris0151:8000
  - lyris0154:8001
  - lyris0156:8002
generation_servers:
  num_instances: 1
  urls:
  - lyris0146:8000
hostname: lyris0146
port: 8333
