backend: pytorch
context_servers:
  num_instances: 1
  urls:
  - <node14_placeholder>:8000
generation_servers:
  num_instances: 7
  urls:
  - <node0_placeholder>:8000
  - <node2_placeholder>:8001
  - <node4_placeholder>:8002
  - <node6_placeholder>:8003
  - <node8_placeholder>:8004
  - <node10_placeholder>:8005
  - <node12_placeholder>:8006
hostname: <node0_placeholder>
port: 8333
