backend: pytorch
context_servers:
  num_instances: 3
  urls:
  - lyris0049:8000
  - lyris0051:8001
  - lyris0053:8002
generation_servers:
  num_instances: 1
  urls:
  - lyris0045:8000
hostname: lyris0045
port: 8333
