cache_transceiver_config:
  backend: DEFAULT
  max_tokens_in_buffer: 131104
  transceiver_runtime: CPP
cuda_graph_config: null
disable_overlap_scheduler: true
enable_attention_dp: false
kv_cache_config:
  dtype: fp8
  enable_block_reuse: false
  free_gpu_memory_fraction: 0.4
max_batch_size: 1
max_num_tokens: 131104
max_seq_len: 131104
moe_config:
  backend: TRTLLM
moe_expert_parallel_size: 1
pipeline_parallel_size: 8
print_iter_log: true
speculative_config:
  decoding_type: MTP
  num_nextn_predict_layers: 2
tensor_parallel_size: 1
